### ISSUE TITLE
Call to undefined method locate_wp_content()

### ISSUE THREAD

**Issue by tyrann0us** [pelmered/composer-plugin-language-update#3]
`scripts` property of `composer.json`:
```
"scripts": {
  "post-package-install": [
    "AngryCreative\\WPLanguageUpdater\\PostUpdateLanguageUpdate::install_t10ns"
  ],
  "post-package-update": [
    "AngryCreative\\WPLanguageUpdater\\PostUpdateLanguageUpdate::update_t10ns"
  ]
}
```

When running `composer update` I get the following fatal error:
```
> AngryCreative\WPLanguageUpdater\PostUpdateLanguageUpdate::update_t10ns
 
 Fatal error: Uncaught Error: Call to undefined method AngryCreative\WPLanguageUpdater\PostUpdateLanguageUpdate::locate_wp_content()
in /Applications/AMPPS/www/mtrix.test/vendor/pelmered/composer-plugin-language-update/src/PostUpdateLanguageUpdate.php:110
 Stack trace:
 #0 /Applications/AMPPS/www/mtrix.test/vendor/pelmered/composer-plugin-language-update/src/PostUpdateLanguageUpdate.php(75):
AngryCreative\WPLanguageUpdater\PostUpdateLanguageUpdate::set_config()
 #1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(292):
AngryCreative\WPLanguageUpdater\PostUpdateLanguageUpdate::update_t10ns(Object(Composer\Installer\PackageEvent))
 #2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(215):
Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('AngryCreative\\W...', 'update_t10ns', Object(Composer\Installer\PackageEvent))
 #3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(116):
Composer\EventDispatcher\EventDispatcher->doDispatc in /Applications/AMPPS/www/mtrix.test/vendor/pelmered/composer-plugin-language-update/src/PostUpdateLanguageUpdate.php on line 110
 Failed to update packages for  ./composer.json.
```
I'm using https://github.com/dnaber-de/wpstarter-boilerplate if that's relevant.
Related: #2.

**Comment by pelmered** [comment]
This is fixed in 0c953a214c0ef176582a8e14d0590522334a599b and will be available in the next release `0.3.0`.
